# Generated by Django 5.1 on 2024-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_supervisor_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gradyear',
            field=models.PositiveIntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028')]),
        ),
    ]
