# Generated by Django 5.1.1 on 2024-11-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_user_gradyear"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("pointsreward", models.IntegerField()),
                ("description", models.TextField()),
                ("validationmethod", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="minor",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
