# Generated by Django 5.1.2 on 2024-10-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_gradyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='minor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
