# Generated by Django 5.1.2 on 2024-11-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_minor'),
        ('main', '0008_campaign_alter_user_minor'),
    ]

    operations = [
    ]
