# Generated by Django 5.1.2 on 2024-11-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20241101_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curent_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='pointsreward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
