# Generated by Django 5.1.2 on 2024-11-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_campaign_id_campaigncompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
