# Generated by Django 5.1.2 on 2024-11-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_campaigncompletioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncompletioninfo',
            name='location',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
