# Generated by Django 5.1.1 on 2024-11-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_campaigncompletioninfo_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("pointsrequired", models.PositiveIntegerField(default=0)),
                ("description", models.TextField()),
            ],
        ),
    ]
