# Generated by Django 5.1.1 on 2024-12-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_user_redeemed_rewards_rewardredeeminfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                default="default_avatar.png", upload_to="profile_pictures/"
            ),
        ),
    ]
