# Generated by Django 5.1.3 on 2024-12-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
