# Generated by Django 5.1.2 on 2024-12-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reward',
            name='redeemedamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='totalamount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reward',
            name='userredeemlimit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='rewardredeeminfo',
            unique_together={('user', 'reward', 'redeemed_at')},
        ),
    ]
