# Generated by Django 5.1.1 on 2024-12-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_reward_expired_reward_redeemedamount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reward_images/"),
        ),
    ]
